FROM node:20

RUN npm install -g pnpm

WORKDIR /usr/app

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install --frozen-lockfile

COPY ./prisma ./prisma

COPY . .

RUN pnpm run build

EXPOSE 4200

CMD ["pnpm", "run", "start:prod"]